version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: web_dns_dev
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - 3306:3306
      networks:
        integration_network:
          aliases:
            - db_host
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/web_dns_app
    environment:
      DATABASE_HOST: db_host
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: web_dns_dev
    ports:
      - "3000:3000"
    networks:
      integration_network:
    depends_on:
      - mysql
    links:
      - mysql:db_host
networks:
  integration_network:
